// This file is generated by Slice Machine. Update with care!

import ContentGrid from './ContentGrid';
import EditorialSection from './EditorialSection';
import FeaturedContent from './FeaturedContent';
import HeadingSection from './HeadingSection';
import HeroAlt from './HeroAlt';
import HeroSection from './HeroSection';
import ImageSection from './ImageSection';
import ListSection from './ListSection';
import LogosSection from './LogosSection';
import QuoteSection from './QuoteSection';
import TextAlt from './TextAlt';
import TextGrid from './TextGrid';
import TextSection from './TextSection';

export {
	ContentGrid,
	EditorialSection,
	FeaturedContent,
	HeadingSection,
	HeroAlt,
	HeroSection,
	ImageSection,
	ListSection,
	LogosSection,
	QuoteSection,
	TextAlt,
	TextGrid,
	TextSection,
};

export const components = {
	content_grid: ContentGrid,
	editorial_section: EditorialSection,
	featured_content: FeaturedContent,
	heading_section: HeadingSection,
	hero_alt: HeroAlt,
	hero_section: HeroSection,
	image_section: ImageSection,
	list_section: ListSection,
	logos_section: LogosSection,
	quote_section: QuoteSection,
	text_alt: TextAlt,
	text_grid: TextGrid,
	text_section: TextSection,
};
